id: I0472E4D4
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:27:40.254106
last_modified: 2023-02-08 15:27:40.254216
source_metadata:
  title: 'PP: Vajracchedikā Prajñāpāramitā'
  language: sa
bases:
  BC39:
    base_file: BC39.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
